'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Vodacom
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://soap.gsm.co.za/", ConfigurationName:="Vodacom.XML2SMSServiceSoap")>  _
    Public Interface XML2SMSServiceSoap
        
        'CODEGEN: Generating message contract since element name username from namespace https://soap.gsm.co.za/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/SendSMS", ReplyAction:="*")>  _
        Function SendSMS(ByVal request As Vodacom.SendSMSRequest) As Vodacom.SendSMSResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/SendSMS", ReplyAction:="*")>  _
        Function SendSMSAsync(ByVal request As Vodacom.SendSMSRequest) As System.Threading.Tasks.Task(Of Vodacom.SendSMSResponse)
        
        'CODEGEN: Generating message contract since element name username from namespace https://soap.gsm.co.za/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/SendEMS", ReplyAction:="*")>  _
        Function SendEMS(ByVal request As Vodacom.SendEMSRequest) As Vodacom.SendEMSResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/SendEMS", ReplyAction:="*")>  _
        Function SendEMSAsync(ByVal request As Vodacom.SendEMSRequest) As System.Threading.Tasks.Task(Of Vodacom.SendEMSResponse)
        
        'CODEGEN: Generating message contract since element name username from namespace https://soap.gsm.co.za/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/RecvLogByKey", ReplyAction:="*")>  _
        Function RecvLogByKey(ByVal request As Vodacom.RecvLogByKeyRequest) As Vodacom.RecvLogByKeyResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/RecvLogByKey", ReplyAction:="*")>  _
        Function RecvLogByKeyAsync(ByVal request As Vodacom.RecvLogByKeyRequest) As System.Threading.Tasks.Task(Of Vodacom.RecvLogByKeyResponse)
        
        'CODEGEN: Generating message contract since element name username from namespace https://soap.gsm.co.za/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/RecvLogByWatermark", ReplyAction:="*")>  _
        Function RecvLogByWatermark(ByVal request As Vodacom.RecvLogByWatermarkRequest) As Vodacom.RecvLogByWatermarkResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/RecvLogByWatermark", ReplyAction:="*")>  _
        Function RecvLogByWatermarkAsync(ByVal request As Vodacom.RecvLogByWatermarkRequest) As System.Threading.Tasks.Task(Of Vodacom.RecvLogByWatermarkResponse)
        
        'CODEGEN: Generating message contract since element name username from namespace https://soap.gsm.co.za/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/RecvLogByDate", ReplyAction:="*")>  _
        Function RecvLogByDate(ByVal request As Vodacom.RecvLogByDateRequest) As Vodacom.RecvLogByDateResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/RecvLogByDate", ReplyAction:="*")>  _
        Function RecvLogByDateAsync(ByVal request As Vodacom.RecvLogByDateRequest) As System.Threading.Tasks.Task(Of Vodacom.RecvLogByDateResponse)
        
        'CODEGEN: Generating message contract since element name username from namespace https://soap.gsm.co.za/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/SendLogByKey", ReplyAction:="*")>  _
        Function SendLogByKey(ByVal request As Vodacom.SendLogByKeyRequest) As Vodacom.SendLogByKeyResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/SendLogByKey", ReplyAction:="*")>  _
        Function SendLogByKeyAsync(ByVal request As Vodacom.SendLogByKeyRequest) As System.Threading.Tasks.Task(Of Vodacom.SendLogByKeyResponse)
        
        'CODEGEN: Generating message contract since element name username from namespace https://soap.gsm.co.za/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/SendLogByWatermark", ReplyAction:="*")>  _
        Function SendLogByWatermark(ByVal request As Vodacom.SendLogByWatermarkRequest) As Vodacom.SendLogByWatermarkResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/SendLogByWatermark", ReplyAction:="*")>  _
        Function SendLogByWatermarkAsync(ByVal request As Vodacom.SendLogByWatermarkRequest) As System.Threading.Tasks.Task(Of Vodacom.SendLogByWatermarkResponse)
        
        'CODEGEN: Generating message contract since element name username from namespace https://soap.gsm.co.za/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/SendLogByDate", ReplyAction:="*")>  _
        Function SendLogByDate(ByVal request As Vodacom.SendLogByDateRequest) As Vodacom.SendLogByDateResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/SendLogByDate", ReplyAction:="*")>  _
        Function SendLogByDateAsync(ByVal request As Vodacom.SendLogByDateRequest) As System.Threading.Tasks.Task(Of Vodacom.SendLogByDateResponse)
        
        'CODEGEN: Generating message contract since element name batchcols from namespace https://soap.gsm.co.za/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/SendMultiSMS", ReplyAction:="*")>  _
        Function SendMultiSMS(ByVal request As Vodacom.SendMultiSMSRequest) As Vodacom.SendMultiSMSResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/SendMultiSMS", ReplyAction:="*")>  _
        Function SendMultiSMSAsync(ByVal request As Vodacom.SendMultiSMSRequest) As System.Threading.Tasks.Task(Of Vodacom.SendMultiSMSResponse)
        
        'CODEGEN: Generating message contract since element name batchcols from namespace https://soap.gsm.co.za/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/SendMultiEMS", ReplyAction:="*")>  _
        Function SendMultiEMS(ByVal request As Vodacom.SendMultiEMSRequest) As Vodacom.SendMultiEMSResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://soap.gsm.co.za/SendMultiEMS", ReplyAction:="*")>  _
        Function SendMultiEMSAsync(ByVal request As Vodacom.SendMultiEMSRequest) As System.Threading.Tasks.Task(Of Vodacom.SendMultiEMSResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendSMSRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendSMS", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.SendSMSRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.SendSMSRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class SendSMSRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public number As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public message As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal username As String, ByVal password As String, ByVal number As String, ByVal message As String)
            MyBase.New
            Me.username = username
            Me.password = password
            Me.number = number
            Me.message = message
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendSMSResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendSMSResponse", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.SendSMSResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.SendSMSResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class SendSMSResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SendSMSResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SendSMSResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.SendSMSResult = SendSMSResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendEMSRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendEMS", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.SendEMSRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.SendEMSRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class SendEMSRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public number As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public message As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal username As String, ByVal password As String, ByVal number As String, ByVal message As String)
            MyBase.New
            Me.username = username
            Me.password = password
            Me.number = number
            Me.message = message
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendEMSResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendEMSResponse", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.SendEMSResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.SendEMSResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class SendEMSResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SendEMSResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SendEMSResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.SendEMSResult = SendEMSResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecvLogByKeyRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecvLogByKey", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.RecvLogByKeyRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.RecvLogByKeyRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class RecvLogByKeyRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public key As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal username As String, ByVal password As String, ByVal key As String)
            MyBase.New
            Me.username = username
            Me.password = password
            Me.key = key
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecvLogByKeyResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecvLogByKeyResponse", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.RecvLogByKeyResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.RecvLogByKeyResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class RecvLogByKeyResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RecvLogByKeyResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RecvLogByKeyResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.RecvLogByKeyResult = RecvLogByKeyResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecvLogByWatermarkRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecvLogByWatermark", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.RecvLogByWatermarkRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.RecvLogByWatermarkRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class RecvLogByWatermarkRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public watermark As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal username As String, ByVal password As String, ByVal watermark As String)
            MyBase.New
            Me.username = username
            Me.password = password
            Me.watermark = watermark
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecvLogByWatermarkResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecvLogByWatermarkResponse", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.RecvLogByWatermarkResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.RecvLogByWatermarkResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class RecvLogByWatermarkResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RecvLogByWatermarkResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RecvLogByWatermarkResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.RecvLogByWatermarkResult = RecvLogByWatermarkResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecvLogByDateRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecvLogByDate", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.RecvLogByDateRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.RecvLogByDateRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class RecvLogByDateRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public startdate As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public enddate As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal username As String, ByVal password As String, ByVal startdate As String, ByVal enddate As String)
            MyBase.New
            Me.username = username
            Me.password = password
            Me.startdate = startdate
            Me.enddate = enddate
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RecvLogByDateResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RecvLogByDateResponse", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.RecvLogByDateResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.RecvLogByDateResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class RecvLogByDateResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RecvLogByDateResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RecvLogByDateResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.RecvLogByDateResult = RecvLogByDateResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendLogByKeyRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendLogByKey", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.SendLogByKeyRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.SendLogByKeyRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class SendLogByKeyRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public key As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal username As String, ByVal password As String, ByVal key As String)
            MyBase.New
            Me.username = username
            Me.password = password
            Me.key = key
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendLogByKeyResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendLogByKeyResponse", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.SendLogByKeyResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.SendLogByKeyResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class SendLogByKeyResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SendLogByKeyResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SendLogByKeyResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.SendLogByKeyResult = SendLogByKeyResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendLogByWatermarkRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendLogByWatermark", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.SendLogByWatermarkRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.SendLogByWatermarkRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class SendLogByWatermarkRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public watermark As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal username As String, ByVal password As String, ByVal watermark As String)
            MyBase.New
            Me.username = username
            Me.password = password
            Me.watermark = watermark
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendLogByWatermarkResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendLogByWatermarkResponse", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.SendLogByWatermarkResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.SendLogByWatermarkResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class SendLogByWatermarkResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SendLogByWatermarkResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SendLogByWatermarkResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.SendLogByWatermarkResult = SendLogByWatermarkResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendLogByDateRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendLogByDate", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.SendLogByDateRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.SendLogByDateRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class SendLogByDateRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public startdate As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public enddate As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal username As String, ByVal password As String, ByVal startdate As String, ByVal enddate As String)
            MyBase.New
            Me.username = username
            Me.password = password
            Me.startdate = startdate
            Me.enddate = enddate
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendLogByDateResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendLogByDateResponse", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.SendLogByDateResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.SendLogByDateResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class SendLogByDateResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SendLogByDateResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SendLogByDateResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.SendLogByDateResult = SendLogByDateResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendMultiSMSRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendMultiSMS", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.SendMultiSMSRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.SendMultiSMSRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class SendMultiSMSRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public batchcols As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public batch As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public gwusername As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public gwpassword As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal batchcols As String, ByVal batch As String, ByVal gwusername As String, ByVal gwpassword As String)
            MyBase.New
            Me.batchcols = batchcols
            Me.batch = batch
            Me.gwusername = gwusername
            Me.gwpassword = gwpassword
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendMultiSMSResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendMultiSMSResponse", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.SendMultiSMSResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.SendMultiSMSResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class SendMultiSMSResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SendMultiSMSResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SendMultiSMSResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.SendMultiSMSResult = SendMultiSMSResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendMultiEMSRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendMultiEMS", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.SendMultiEMSRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.SendMultiEMSRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class SendMultiEMSRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public batchcols As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public batch As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public gwusername As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public gwpassword As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal batchcols As String, ByVal batch As String, ByVal gwusername As String, ByVal gwpassword As String)
            MyBase.New
            Me.batchcols = batchcols
            Me.batch = batch
            Me.gwusername = gwusername
            Me.gwpassword = gwpassword
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendMultiEMSResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SendMultiEMSResponse", [Namespace]:="https://soap.gsm.co.za/", Order:=0)>  _
        Public Body As Vodacom.SendMultiEMSResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Vodacom.SendMultiEMSResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://soap.gsm.co.za/")>  _
    Partial Public Class SendMultiEMSResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SendMultiEMSResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SendMultiEMSResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.SendMultiEMSResult = SendMultiEMSResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface XML2SMSServiceSoapChannel
        Inherits Vodacom.XML2SMSServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class XML2SMSServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of Vodacom.XML2SMSServiceSoap)
        Implements Vodacom.XML2SMSServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_SendSMS(ByVal request As Vodacom.SendSMSRequest) As Vodacom.SendSMSResponse Implements Vodacom.XML2SMSServiceSoap.SendSMS
            Return MyBase.Channel.SendSMS(request)
        End Function
        
        Public Function SendSMS(ByVal username As String, ByVal password As String, ByVal number As String, ByVal message As String) As System.Xml.Linq.XElement
            Dim inValue As Vodacom.SendSMSRequest = New Vodacom.SendSMSRequest()
            inValue.Body = New Vodacom.SendSMSRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.number = number
            inValue.Body.message = message
            Dim retVal As Vodacom.SendSMSResponse = CType(Me,Vodacom.XML2SMSServiceSoap).SendSMS(inValue)
            Return retVal.Body.SendSMSResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_SendSMSAsync(ByVal request As Vodacom.SendSMSRequest) As System.Threading.Tasks.Task(Of Vodacom.SendSMSResponse) Implements Vodacom.XML2SMSServiceSoap.SendSMSAsync
            Return MyBase.Channel.SendSMSAsync(request)
        End Function
        
        Public Function SendSMSAsync(ByVal username As String, ByVal password As String, ByVal number As String, ByVal message As String) As System.Threading.Tasks.Task(Of Vodacom.SendSMSResponse)
            Dim inValue As Vodacom.SendSMSRequest = New Vodacom.SendSMSRequest()
            inValue.Body = New Vodacom.SendSMSRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.number = number
            inValue.Body.message = message
            Return CType(Me,Vodacom.XML2SMSServiceSoap).SendSMSAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_SendEMS(ByVal request As Vodacom.SendEMSRequest) As Vodacom.SendEMSResponse Implements Vodacom.XML2SMSServiceSoap.SendEMS
            Return MyBase.Channel.SendEMS(request)
        End Function
        
        Public Function SendEMS(ByVal username As String, ByVal password As String, ByVal number As String, ByVal message As String) As System.Xml.Linq.XElement
            Dim inValue As Vodacom.SendEMSRequest = New Vodacom.SendEMSRequest()
            inValue.Body = New Vodacom.SendEMSRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.number = number
            inValue.Body.message = message
            Dim retVal As Vodacom.SendEMSResponse = CType(Me,Vodacom.XML2SMSServiceSoap).SendEMS(inValue)
            Return retVal.Body.SendEMSResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_SendEMSAsync(ByVal request As Vodacom.SendEMSRequest) As System.Threading.Tasks.Task(Of Vodacom.SendEMSResponse) Implements Vodacom.XML2SMSServiceSoap.SendEMSAsync
            Return MyBase.Channel.SendEMSAsync(request)
        End Function
        
        Public Function SendEMSAsync(ByVal username As String, ByVal password As String, ByVal number As String, ByVal message As String) As System.Threading.Tasks.Task(Of Vodacom.SendEMSResponse)
            Dim inValue As Vodacom.SendEMSRequest = New Vodacom.SendEMSRequest()
            inValue.Body = New Vodacom.SendEMSRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.number = number
            inValue.Body.message = message
            Return CType(Me,Vodacom.XML2SMSServiceSoap).SendEMSAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_RecvLogByKey(ByVal request As Vodacom.RecvLogByKeyRequest) As Vodacom.RecvLogByKeyResponse Implements Vodacom.XML2SMSServiceSoap.RecvLogByKey
            Return MyBase.Channel.RecvLogByKey(request)
        End Function
        
        Public Function RecvLogByKey(ByVal username As String, ByVal password As String, ByVal key As String) As System.Xml.Linq.XElement
            Dim inValue As Vodacom.RecvLogByKeyRequest = New Vodacom.RecvLogByKeyRequest()
            inValue.Body = New Vodacom.RecvLogByKeyRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.key = key
            Dim retVal As Vodacom.RecvLogByKeyResponse = CType(Me,Vodacom.XML2SMSServiceSoap).RecvLogByKey(inValue)
            Return retVal.Body.RecvLogByKeyResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_RecvLogByKeyAsync(ByVal request As Vodacom.RecvLogByKeyRequest) As System.Threading.Tasks.Task(Of Vodacom.RecvLogByKeyResponse) Implements Vodacom.XML2SMSServiceSoap.RecvLogByKeyAsync
            Return MyBase.Channel.RecvLogByKeyAsync(request)
        End Function
        
        Public Function RecvLogByKeyAsync(ByVal username As String, ByVal password As String, ByVal key As String) As System.Threading.Tasks.Task(Of Vodacom.RecvLogByKeyResponse)
            Dim inValue As Vodacom.RecvLogByKeyRequest = New Vodacom.RecvLogByKeyRequest()
            inValue.Body = New Vodacom.RecvLogByKeyRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.key = key
            Return CType(Me,Vodacom.XML2SMSServiceSoap).RecvLogByKeyAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_RecvLogByWatermark(ByVal request As Vodacom.RecvLogByWatermarkRequest) As Vodacom.RecvLogByWatermarkResponse Implements Vodacom.XML2SMSServiceSoap.RecvLogByWatermark
            Return MyBase.Channel.RecvLogByWatermark(request)
        End Function
        
        Public Function RecvLogByWatermark(ByVal username As String, ByVal password As String, ByVal watermark As String) As System.Xml.Linq.XElement
            Dim inValue As Vodacom.RecvLogByWatermarkRequest = New Vodacom.RecvLogByWatermarkRequest()
            inValue.Body = New Vodacom.RecvLogByWatermarkRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.watermark = watermark
            Dim retVal As Vodacom.RecvLogByWatermarkResponse = CType(Me,Vodacom.XML2SMSServiceSoap).RecvLogByWatermark(inValue)
            Return retVal.Body.RecvLogByWatermarkResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_RecvLogByWatermarkAsync(ByVal request As Vodacom.RecvLogByWatermarkRequest) As System.Threading.Tasks.Task(Of Vodacom.RecvLogByWatermarkResponse) Implements Vodacom.XML2SMSServiceSoap.RecvLogByWatermarkAsync
            Return MyBase.Channel.RecvLogByWatermarkAsync(request)
        End Function
        
        Public Function RecvLogByWatermarkAsync(ByVal username As String, ByVal password As String, ByVal watermark As String) As System.Threading.Tasks.Task(Of Vodacom.RecvLogByWatermarkResponse)
            Dim inValue As Vodacom.RecvLogByWatermarkRequest = New Vodacom.RecvLogByWatermarkRequest()
            inValue.Body = New Vodacom.RecvLogByWatermarkRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.watermark = watermark
            Return CType(Me,Vodacom.XML2SMSServiceSoap).RecvLogByWatermarkAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_RecvLogByDate(ByVal request As Vodacom.RecvLogByDateRequest) As Vodacom.RecvLogByDateResponse Implements Vodacom.XML2SMSServiceSoap.RecvLogByDate
            Return MyBase.Channel.RecvLogByDate(request)
        End Function
        
        Public Function RecvLogByDate(ByVal username As String, ByVal password As String, ByVal startdate As String, ByVal enddate As String) As System.Xml.Linq.XElement
            Dim inValue As Vodacom.RecvLogByDateRequest = New Vodacom.RecvLogByDateRequest()
            inValue.Body = New Vodacom.RecvLogByDateRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.startdate = startdate
            inValue.Body.enddate = enddate
            Dim retVal As Vodacom.RecvLogByDateResponse = CType(Me,Vodacom.XML2SMSServiceSoap).RecvLogByDate(inValue)
            Return retVal.Body.RecvLogByDateResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_RecvLogByDateAsync(ByVal request As Vodacom.RecvLogByDateRequest) As System.Threading.Tasks.Task(Of Vodacom.RecvLogByDateResponse) Implements Vodacom.XML2SMSServiceSoap.RecvLogByDateAsync
            Return MyBase.Channel.RecvLogByDateAsync(request)
        End Function
        
        Public Function RecvLogByDateAsync(ByVal username As String, ByVal password As String, ByVal startdate As String, ByVal enddate As String) As System.Threading.Tasks.Task(Of Vodacom.RecvLogByDateResponse)
            Dim inValue As Vodacom.RecvLogByDateRequest = New Vodacom.RecvLogByDateRequest()
            inValue.Body = New Vodacom.RecvLogByDateRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.startdate = startdate
            inValue.Body.enddate = enddate
            Return CType(Me,Vodacom.XML2SMSServiceSoap).RecvLogByDateAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_SendLogByKey(ByVal request As Vodacom.SendLogByKeyRequest) As Vodacom.SendLogByKeyResponse Implements Vodacom.XML2SMSServiceSoap.SendLogByKey
            Return MyBase.Channel.SendLogByKey(request)
        End Function
        
        Public Function SendLogByKey(ByVal username As String, ByVal password As String, ByVal key As String) As System.Xml.Linq.XElement
            Dim inValue As Vodacom.SendLogByKeyRequest = New Vodacom.SendLogByKeyRequest()
            inValue.Body = New Vodacom.SendLogByKeyRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.key = key
            Dim retVal As Vodacom.SendLogByKeyResponse = CType(Me,Vodacom.XML2SMSServiceSoap).SendLogByKey(inValue)
            Return retVal.Body.SendLogByKeyResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_SendLogByKeyAsync(ByVal request As Vodacom.SendLogByKeyRequest) As System.Threading.Tasks.Task(Of Vodacom.SendLogByKeyResponse) Implements Vodacom.XML2SMSServiceSoap.SendLogByKeyAsync
            Return MyBase.Channel.SendLogByKeyAsync(request)
        End Function
        
        Public Function SendLogByKeyAsync(ByVal username As String, ByVal password As String, ByVal key As String) As System.Threading.Tasks.Task(Of Vodacom.SendLogByKeyResponse)
            Dim inValue As Vodacom.SendLogByKeyRequest = New Vodacom.SendLogByKeyRequest()
            inValue.Body = New Vodacom.SendLogByKeyRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.key = key
            Return CType(Me,Vodacom.XML2SMSServiceSoap).SendLogByKeyAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_SendLogByWatermark(ByVal request As Vodacom.SendLogByWatermarkRequest) As Vodacom.SendLogByWatermarkResponse Implements Vodacom.XML2SMSServiceSoap.SendLogByWatermark
            Return MyBase.Channel.SendLogByWatermark(request)
        End Function
        
        Public Function SendLogByWatermark(ByVal username As String, ByVal password As String, ByVal watermark As String) As System.Xml.Linq.XElement
            Dim inValue As Vodacom.SendLogByWatermarkRequest = New Vodacom.SendLogByWatermarkRequest()
            inValue.Body = New Vodacom.SendLogByWatermarkRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.watermark = watermark
            Dim retVal As Vodacom.SendLogByWatermarkResponse = CType(Me,Vodacom.XML2SMSServiceSoap).SendLogByWatermark(inValue)
            Return retVal.Body.SendLogByWatermarkResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_SendLogByWatermarkAsync(ByVal request As Vodacom.SendLogByWatermarkRequest) As System.Threading.Tasks.Task(Of Vodacom.SendLogByWatermarkResponse) Implements Vodacom.XML2SMSServiceSoap.SendLogByWatermarkAsync
            Return MyBase.Channel.SendLogByWatermarkAsync(request)
        End Function
        
        Public Function SendLogByWatermarkAsync(ByVal username As String, ByVal password As String, ByVal watermark As String) As System.Threading.Tasks.Task(Of Vodacom.SendLogByWatermarkResponse)
            Dim inValue As Vodacom.SendLogByWatermarkRequest = New Vodacom.SendLogByWatermarkRequest()
            inValue.Body = New Vodacom.SendLogByWatermarkRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.watermark = watermark
            Return CType(Me,Vodacom.XML2SMSServiceSoap).SendLogByWatermarkAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_SendLogByDate(ByVal request As Vodacom.SendLogByDateRequest) As Vodacom.SendLogByDateResponse Implements Vodacom.XML2SMSServiceSoap.SendLogByDate
            Return MyBase.Channel.SendLogByDate(request)
        End Function
        
        Public Function SendLogByDate(ByVal username As String, ByVal password As String, ByVal startdate As String, ByVal enddate As String) As System.Xml.Linq.XElement
            Dim inValue As Vodacom.SendLogByDateRequest = New Vodacom.SendLogByDateRequest()
            inValue.Body = New Vodacom.SendLogByDateRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.startdate = startdate
            inValue.Body.enddate = enddate
            Dim retVal As Vodacom.SendLogByDateResponse = CType(Me,Vodacom.XML2SMSServiceSoap).SendLogByDate(inValue)
            Return retVal.Body.SendLogByDateResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_SendLogByDateAsync(ByVal request As Vodacom.SendLogByDateRequest) As System.Threading.Tasks.Task(Of Vodacom.SendLogByDateResponse) Implements Vodacom.XML2SMSServiceSoap.SendLogByDateAsync
            Return MyBase.Channel.SendLogByDateAsync(request)
        End Function
        
        Public Function SendLogByDateAsync(ByVal username As String, ByVal password As String, ByVal startdate As String, ByVal enddate As String) As System.Threading.Tasks.Task(Of Vodacom.SendLogByDateResponse)
            Dim inValue As Vodacom.SendLogByDateRequest = New Vodacom.SendLogByDateRequest()
            inValue.Body = New Vodacom.SendLogByDateRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            inValue.Body.startdate = startdate
            inValue.Body.enddate = enddate
            Return CType(Me,Vodacom.XML2SMSServiceSoap).SendLogByDateAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_SendMultiSMS(ByVal request As Vodacom.SendMultiSMSRequest) As Vodacom.SendMultiSMSResponse Implements Vodacom.XML2SMSServiceSoap.SendMultiSMS
            Return MyBase.Channel.SendMultiSMS(request)
        End Function
        
        Public Function SendMultiSMS(ByVal batchcols As String, ByVal batch As String, ByVal gwusername As String, ByVal gwpassword As String) As System.Xml.Linq.XElement
            Dim inValue As Vodacom.SendMultiSMSRequest = New Vodacom.SendMultiSMSRequest()
            inValue.Body = New Vodacom.SendMultiSMSRequestBody()
            inValue.Body.batchcols = batchcols
            inValue.Body.batch = batch
            inValue.Body.gwusername = gwusername
            inValue.Body.gwpassword = gwpassword
            Dim retVal As Vodacom.SendMultiSMSResponse = CType(Me,Vodacom.XML2SMSServiceSoap).SendMultiSMS(inValue)
            Return retVal.Body.SendMultiSMSResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_SendMultiSMSAsync(ByVal request As Vodacom.SendMultiSMSRequest) As System.Threading.Tasks.Task(Of Vodacom.SendMultiSMSResponse) Implements Vodacom.XML2SMSServiceSoap.SendMultiSMSAsync
            Return MyBase.Channel.SendMultiSMSAsync(request)
        End Function
        
        Public Function SendMultiSMSAsync(ByVal batchcols As String, ByVal batch As String, ByVal gwusername As String, ByVal gwpassword As String) As System.Threading.Tasks.Task(Of Vodacom.SendMultiSMSResponse)
            Dim inValue As Vodacom.SendMultiSMSRequest = New Vodacom.SendMultiSMSRequest()
            inValue.Body = New Vodacom.SendMultiSMSRequestBody()
            inValue.Body.batchcols = batchcols
            inValue.Body.batch = batch
            inValue.Body.gwusername = gwusername
            inValue.Body.gwpassword = gwpassword
            Return CType(Me,Vodacom.XML2SMSServiceSoap).SendMultiSMSAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_SendMultiEMS(ByVal request As Vodacom.SendMultiEMSRequest) As Vodacom.SendMultiEMSResponse Implements Vodacom.XML2SMSServiceSoap.SendMultiEMS
            Return MyBase.Channel.SendMultiEMS(request)
        End Function
        
        Public Function SendMultiEMS(ByVal batchcols As String, ByVal batch As String, ByVal gwusername As String, ByVal gwpassword As String) As System.Xml.Linq.XElement
            Dim inValue As Vodacom.SendMultiEMSRequest = New Vodacom.SendMultiEMSRequest()
            inValue.Body = New Vodacom.SendMultiEMSRequestBody()
            inValue.Body.batchcols = batchcols
            inValue.Body.batch = batch
            inValue.Body.gwusername = gwusername
            inValue.Body.gwpassword = gwpassword
            Dim retVal As Vodacom.SendMultiEMSResponse = CType(Me,Vodacom.XML2SMSServiceSoap).SendMultiEMS(inValue)
            Return retVal.Body.SendMultiEMSResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vodacom_XML2SMSServiceSoap_SendMultiEMSAsync(ByVal request As Vodacom.SendMultiEMSRequest) As System.Threading.Tasks.Task(Of Vodacom.SendMultiEMSResponse) Implements Vodacom.XML2SMSServiceSoap.SendMultiEMSAsync
            Return MyBase.Channel.SendMultiEMSAsync(request)
        End Function
        
        Public Function SendMultiEMSAsync(ByVal batchcols As String, ByVal batch As String, ByVal gwusername As String, ByVal gwpassword As String) As System.Threading.Tasks.Task(Of Vodacom.SendMultiEMSResponse)
            Dim inValue As Vodacom.SendMultiEMSRequest = New Vodacom.SendMultiEMSRequest()
            inValue.Body = New Vodacom.SendMultiEMSRequestBody()
            inValue.Body.batchcols = batchcols
            inValue.Body.batch = batch
            inValue.Body.gwusername = gwusername
            inValue.Body.gwpassword = gwpassword
            Return CType(Me,Vodacom.XML2SMSServiceSoap).SendMultiEMSAsync(inValue)
        End Function
    End Class
End Namespace
